[project]
name = "bloomfilter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitarray>=3.0.0",
    "faker>=35.2.0",
    "mmh3>=5.1.0",
]
